### ISSUE TITLE
not work, thanks for you help!

### ISSUE THREAD

**Issue by venturitsoft** [AnatolyKabakov1983/DownloadFiles#1]
Hello, ajax does not work to show table of files to download

![Download_01](https://user-images.githubusercontent.com/26033602/59019969-a32bff00-880e-11e9-8009-a3aaaf98be46.jpg)
![Download_02](https://user-images.githubusercontent.com/26033602/59019970-a32bff00-880e-11e9-9ad7-ddcbe23a544a.jpg)
![Download_03](https://user-images.githubusercontent.com/26033602/59019971-a32bff00-880e-11e9-916a-0fc5e5dd9350.jpg)
![Download_04](https://user-images.githubusercontent.com/26033602/59019972-a32bff00-880e-11e9-837a-e36a62227edc.jpg)
![Download_05](https://user-images.githubusercontent.com/26033602/59019973-a32bff00-880e-11e9-9acc-fa9140ea797f.jpg)
![Download_06](https://user-images.githubusercontent.com/26033602/59019974-a32bff00-880e-11e9-9a36-ffc6ed111da6.jpg)
![Download_07](https://user-images.githubusercontent.com/26033602/59019975-a3c49580-880e-11e9-91f5-b9268f09014d.jpg)

**Comment by AnatolyKabakov1983** [comment]
Hello!
Thanks for the feedback!

Script download-files.js is not blocked in the browser?

**Comment by venturitsoft** [comment]
Hi Anatoly
no, I do not see it blocked

please thank you can enter this mantis demo with the following data

http://sgep.vt2.venturitsoft.com:81/_demo/mantisbt-2.21.0/manage_plugin_page.php

user:
demo_adm

pass:
demo

![01](https://user-images.githubusercontent.com/26033602/59315016-7ac45a80-8c7d-11e9-9eb1-d31a9f938ad7.jpg)
![02](https://user-images.githubusercontent.com/26033602/59315017-7ac45a80-8c7d-11e9-8234-5b366a7932e8.jpg)
![03](https://user-images.githubusercontent.com/26033602/59315018-7ac45a80-8c7d-11e9-9aec-06874fc1397c.jpg)

I am very attentive to your support for Anatoly review

thanks

Carlos Felipe

**Comment by AnatolyKabakov1983** [comment]
Hi,

The plugin requires [jQueryUI plugin](https://github.com/mantisbt-plugins/jQuery-UI) 
    version 1.8 or higher - I corrected the description

**Comment by AnatolyKabakov1983** [comment]
Removed link to plugin page

**Comment by venturitsoft** [comment]
Excellent thank you very much
everything works!

regards Anatoly
